### ISSUE TITLE
General review

### ISSUE THREAD

**Issue by unjapones** [protofire/op-middleware#13]
Tasks:

- Perform general code review.
- Write down improvement suggestions in comment.

**Comment by mariano-aguero** [comment]
First of all, good work! I will give you some advices or feedback about the repository

- Fix a "typo" in the readme file, says `expressed` and should say `express`. The `docker-compose.yaml` file is written in a gist, I think it would be better that it exist in the repository, what do you think about it?
- A good security practice is to use [helmet](https://helmetjs.github.io/)
- Add [postman](https://www.postman.com/) with the existing endpoints and headers, will be helpful as documentation
- I think the use of arrow functions make the code structure more compact and keep the lexical context of the root function. Maybe we can update some parts of the code.
- This is not a MUST, Update the folder name `model` to `models`. Another suggestion is to rename the folder `util` to `helpers` or `utils`.

For the future:
 - Separate Express `app` and `server`. Avoid defining the entire Express app in a single file, separate your `Express` definition . For even better structure, locate your API declaration within components.
 Small example:
 ```
...
const app = require('./config/express')
const mongoose = require('./config/mongoose')
...
```
- To prevent an API from being overwhelmed, just in case of too many requests, we can add some kind of rate limit.

**Comment by unjapones** [comment]
:+1:  @mariano-aguero . Will create issues and group the tasks accordingly later.
Closing this task-issue you have assigned so you don't have anything in progress here.
Thank you!
