### ISSUE TITLE
Add DELETE /storage/cid endpoint

### ISSUE THREAD

**Issue by unjapones** [protofire/op-middleware#8]
The endpoint will be used to cancel a file storage operation that is still in progres.

**Comment by unjapones** [comment]
This feature is not going to be implemented. It looks like there is no straight-forward/easy way to cancel (through Powergate) a storage deal once it started. The feature is not crucial, and may be something similar can be implemented in the future though.

**Comment by cmalfesi** [comment]
Is it possible that we cancel the process on user side but the process in background just continues running and we don't take care of the results? Even, losing the gas price.

**Comment by unjapones** [comment]
If the upload of the file to the middleware is cancelled in the middle _because of reasons_, then no action should take place on Filecoin (the execution won't even reach  the code that interacts with Powergate) and no gas/FIL or anything should be wasted. 
Does this answer the questions?
